name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv (fast dependency resolver)
        run: pip install uv
      - name: Install ruff
        run: pip install ruff
      - name: Install dependencies (main + dev)
        run: uv pip install -e .[dev] --system --index-strategy unsafe-best-match
      - name: Lint with ruff
        run: ruff check . --fix
      - name: Install pytest
        run: pip install pytest pytest-cov
      - name: Run tests with pytest
        run: pytest --cov=src --cov-report=term-missing 